//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab8910
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string ID { get; set; }
        public string OrderID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UnitAmount { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Orderss Orderss { get; set; }
    }
}
